### PR TITLE
Time error

### PR DESCRIPTION
**Pull request by Selven81**
hi, when i use esoteric on rg50 i see the time not right on one hour (gmt?)
for example if it is 8 o clock the consolle say 7

### CODE REVIEW

**Comment by gameblabla** [comment]
Hello,
i'm afraid that you made the pull request on the wrong repo. This isn't supported anymore and it was only for the Arcade Mini & RS-97.
Please submit your pull request to podulator's fork 
https://github.com/podulator/esoteric

**Comment by Selven81** [comment]
I do not know how, i've pulled the request on his fork, but i've been redirect ed here

**Comment by gameblabla** [comment]
I just noticed that you were trying to merge podulator's fork commits to here. Why ?
As i said this was only for the Arcade Mini. Why don't you contact him instead if you are encountering issues with Esoteric ? I have nothing to do with it. Who told you that ?

Is this the reason why people recently have been forking this old ass version all suddenly ?

**Comment by Selven81** [comment]
No i've just pushed pull request on esoterico page and i've been redirected here by github, i don't know how to contact podulator directly

**Pull request closed without merging**
